language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.18"
  - "5.14"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y libmail-sendeasy-perl
    - cpanm Test::Pod # optional dependency

install:
    - cpanm -v --installdeps --notest .

script: "perl Build.PL; ./Build test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - ralph@purejava.org
  email:
    on_success: change
    on_failure: always
#env:
