language: perl
perl:
  - "5.18"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
    - sudo apt-get update -q
    - sudo apt-get install -y libmail-sendeasy-perl
    - cpanm Test::Pod # optional dependency

install:
    - cpanm -v --installdeps --notest .

script: "perl Build-FileCheck.PL; ./Build test"
script: "perl Build-SiteUpdate.PL; ./Build test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - ralph@purejava.org
  email:
    on_success: change
    on_failure: always
#env:
